import type { SourceRegistryEntry } from '../bidmanager/types';

/** Tier 1 DFI / regional sources — public deployment registry. No CEAL data. */
export const SOURCE_REGISTRY: SourceRegistryEntry[] = [
  {
    id: 'src-idb-notices',
    kind: 'api',
    name: 'IDB Procurement Notices',
    funder: 'Inter-American Development Bank',
    baseUrl: 'https://www.iadb.org/en/procurement',
    tier: 1,
    countries: ['Regional', 'Caribbean', 'Latin America'],
    pollFrequencyHours: 12,
    enabled: true,
    notes: 'Structured notices via iadb.org procurement portal',
  },
  {
    id: 'src-idb-plans',
    kind: 'api',
    name: 'IDB Procurement Plans',
    funder: 'Inter-American Development Bank',
    baseUrl: 'https://www.iadb.org/en/procurement/procurement-plan',
    tier: 1,
    countries: ['Regional'],
    pollFrequencyHours: 24,
    enabled: true,
    notes: 'Pre-positioning feed — stage=plan watchlist',
  },
  {
    id: 'src-ccree',
    kind: 'scrape',
    name: 'CCREEE Opportunities',
    funder: 'Caribbean Centre for Renewable Energy and Energy Efficiency',
    baseUrl: 'https://www.ccreee.org',
    tier: 1,
    countries: ['Caribbean', 'SIDS'],
    pollFrequencyHours: 24,
    enabled: true,
    notes: 'Regional renewable energy and efficiency tenders',
  },
  {
    id: 'src-caribbean-export',
    kind: 'api',
    name: 'Caribbean Export Development',
    funder: 'Caribbean Export',
    baseUrl: 'https://www.carib-export.com',
    tier: 1,
    countries: ['Caribbean'],
    pollFrequencyHours: 24,
    enabled: true,
    notes: 'Regional trade and development opportunities',
  },
  {
    id: 'src-cdb',
    kind: 'api',
    name: 'Caribbean Development Bank',
    funder: 'CDB',
    baseUrl: 'https://www.caribank.org/procurement',
    tier: 1,
    countries: ['Caribbean'],
    pollFrequencyHours: 24,
    enabled: true,
    notes: 'DFI procurement for borrowing member countries',
  },
  {
    id: 'src-gcf',
    kind: 'api',
    name: 'Green Climate Fund',
    funder: 'GCF',
    baseUrl: 'https://www.greenclimate.fund',
    tier: 1,
    countries: ['Global', 'SIDS'],
    pollFrequencyHours: 48,
    enabled: true,
    notes: 'Readiness and project calls',
  },
  {
    id: 'src-world-bank',
    kind: 'api',
    name: 'World Bank Procurement',
    funder: 'World Bank',
    baseUrl: 'https://www.worldbank.org/en/projects-operations/procurement',
    tier: 1,
    countries: ['Global', 'Caribbean', 'SIDS'],
    pollFrequencyHours: 24,
    enabled: true,
    notes: 'Multilateral DFI tenders and consultant selection',
  },
  {
    id: 'src-ungm',
    kind: 'api',
    name: 'UNGM / UNDP Opportunities',
    funder: 'UNDP',
    baseUrl: 'https://www.ungm.org',
    tier: 1,
    countries: ['Global', 'Caribbean'],
    pollFrequencyHours: 24,
    enabled: true,
    notes: 'UN agency procurement via UNGM portal',
  },
  {
    id: 'src-ted',
    kind: 'api',
    name: 'EU / EDF — TED',
    funder: 'European Union',
    baseUrl: 'https://ted.europa.eu',
    tier: 1,
    countries: ['Global', 'OCT', 'Caribbean'],
    pollFrequencyHours: 48,
    enabled: true,
    notes: 'EU and EDF-funded procurement notices',
  },
  {
    id: 'src-manual',
    kind: 'manual',
    name: 'Manual entry',
    funder: 'Various',
    baseUrl: '',
    tier: 3,
    countries: [],
    pollFrequencyHours: 0,
    enabled: true,
    notes: 'Newspaper notices, network referrals, direct invitations',
  },
];

export function getSource(id: string): SourceRegistryEntry | undefined {
  return SOURCE_REGISTRY.find((s) => s.id === id);
}
