-- Optional Supabase schema for the next version.
-- Paste this into the Supabase SQL Editor.

create table public.threads (
    id bigint generated by default as identity primary key,
    author text not null default 'Anonymous',
    title text not null,
    body text not null,
    created_at timestamptz not null default now()
);

create table public.comments (
    id bigint generated by default as identity primary key,
    thread_id bigint not null references public.threads(id) on delete cascade,
    author text not null default 'Anonymous',
    body text not null,
    created_at timestamptz not null default now()
);

create index comments_thread_id_idx on public.comments(thread_id);

-- Before using this publicly, enable Row Level Security and create policies
-- that match your authentication and moderation plan.
