import { q, d, type InterviewScenario, type JobTrack } from "./track-model";
import { BUSINESS_JOB_TRACKS } from "./business-tracks";
import { EXTRA_BY_TRACK } from "./track-extras";

export type { Debrief, InterviewScenario, JobTrack } from "./track-model";

function withExtras(tracks: JobTrack[]): JobTrack[] {
  return tracks.map((track) => {
    const extra = EXTRA_BY_TRACK[track.slug] ?? [];
    const scenarios = [...track.scenarios, ...extra];
    if (scenarios.length < 20) {
      throw new Error(`Track ${track.slug} has ${scenarios.length} scenarios; need ≥20`);
    }
    return { ...track, scenarios };
  });
}

const CORE_JOB_TRACKS: JobTrack[] = [
  {
    slug: "software-engineer",
    role: "Software Engineer",
    setting: "Series B product company",
    blurb: "Ownership stories, live coding, debugging, and design judgment.",
    scenarios: [
      q(
        "missed-deadline",
        "Behavioral",
        "You missed a ship date",
        12,
        "Accountability under delivery pressure.",
        "Backend SWE screen. Weekly ship cadence; they probe failure without blame.",
        "Tell me about a time a feature you owned missed its release date. What did you do in the 48 hours after you knew you’d miss it?",
        [
          "Name Situation: feature, stakeholder, original date.",
          "Own the miss early — no “QA was slow” as the headline.",
          "Action: re-scope, communicate, protect users.",
          "Result: what shipped, what slipped, process change left behind.",
          "One signal you’d watch earlier next time.",
        ],
        d(
          "Interviewers most want to hear:",
          [
            "That the miss was someone else’s fault",
            "Early ownership plus a concrete recovery plan",
            "That deadlines don’t matter in agile",
            "A long list of tools you used",
          ],
          1,
          "Ownership + recovery beats an unprovable perfect history.",
        ),
      ),
      q(
        "rate-limiter",
        "Coding",
        "Design a rate limiter",
        25,
        "Coding screen as a reliability problem.",
        "API-heavy SWE onsite. Correctness, edges, and how you talk while typing.",
        "Implement an in-memory rate limiter: N requests per user per window. Walk approach first. What breaks at scale?",
        [
          "Clarify fixed vs sliding window, per-user vs IP, reject shape.",
          "Sketch map of user → timestamps or token bucket.",
          "Happy path, then concurrency and memory growth.",
          "Name one production upgrade (Redis) without overbuilding.",
          "Tests: burst at window edge, unknown user, N=0.",
        ],
        d(
          "Before coding you should first:",
          [
            "Pick Redis immediately",
            "Clarify window semantics and reject behavior",
            "Refuse to code without a laptop",
            "Discuss salary bands",
          ],
          1,
          "Ambiguous windows create wrong “done” solutions.",
        ),
      ),
      q(
        "notifications-design",
        "System design",
        "Design notifications",
        30,
        "Multi-channel notification service.",
        "Senior loop for product messaging (email, push, in-app).",
        "How would you design notifications across email, push, and in-app at about 5M MAU, and where do fan-out and failure modes get hard?",
        [
          "Separate functional needs from SLOs.",
          "Producer → queue → workers → providers; isolate failures.",
          "Idempotency keys and preference checks before send.",
          "Fan-out, retries, dead-letter queues.",
          "Metrics: send success, bounce, time-to-inbox.",
        ],
        d(
          "A solid notifications design includes:",
          [
            "A single sync HTTP call to every provider",
            "A queue plus retry/dead-letter strategy",
            "Passwords in the notification payload",
            "Skipping user preferences",
          ],
          1,
          "Providers fail; queues and retries keep reliability.",
        ),
      ),
      q(
        "debug-prod-outage",
        "Behavioral",
        "Production outage at 2am",
        15,
        "Incident response and calm communication.",
        "On-call aware SWE role. They want triage order, not hero stories.",
        "Walk me through a production incident you led. How did you triage, communicate, and prevent recurrence?",
        [
          "Impact first: who is broken, severity, blast radius.",
          "Stabilize before root-causing forever.",
          "Comms: status page / stakeholders on a cadence.",
          "Root cause with evidence, not guesses.",
          "Postmortem: action items with owners and dates.",
        ],
        d(
          "In an outage, the first priority is usually:",
          [
            "Rewriting the whole service",
            "Stabilizing impact and communicating clearly",
            "Assigning blame in Slack",
            "Shipping a new feature to distract users",
          ],
          1,
          "Stabilize + communicate beats premature deep dives.",
        ),
      ),
      q(
        "two-sum-variant",
        "Coding",
        "Pair-sum with constraints",
        20,
        "Classic coding with follow-up constraints.",
        "Phone screen. They escalate from brute force to streaming constraints.",
        "Given an array of integers and a target, how would you determine whether any two numbers sum to the target—and how would your approach change for a memory-bound stream?",
        [
          "Start with clarify: duplicates? indices? sorted?",
          "Brute O(n²), then hash set O(n).",
          "Talk tradeoffs out loud while coding.",
          "Streaming follow-up: maybe keep a bounded window or sketch.",
          "Edge cases: empty, one element, negatives.",
        ],
        d(
          "The usual optimal single-pass approach uses:",
          [
            "Nested loops only",
            "A hash set of complements seen so far",
            "Sorting then ignoring the stream follow-up",
            "Recursion with no memo",
          ],
          1,
          "Hash complements give O(n) time for the classic case.",
        ),
      ),
      q(
        "api-review",
        "Technical",
        "Review a messy API",
        18,
        "API design taste and backward compatibility.",
        "Platform team interview. They show a draft REST endpoint and ask what you’d change.",
        "Here’s a draft `/users/getAllData?id=`. What would you change before shipping, and why?",
        [
          "Naming: resource nouns, HTTP verbs, no verbs in path.",
          "AuthZ: who can call this, PII exposure.",
          "Pagination, filtering, field selection.",
          "Versioning / compatibility if clients exist.",
          "Errors: consistent status codes and error body.",
        ],
        d(
          "A strong API review almost always covers:",
          [
            "Only prettier OpenAPI colors",
            "Auth, shape, pagination, and error contracts",
            "Removing all documentation",
            "Hardcoding one customer’s fields",
          ],
          1,
          "Taste shows in contracts clients can rely on.",
        ),
      ),
      q(
        "conflict-pr",
        "Behavioral",
        "Disagreement on a PR",
        12,
        "Technical disagreement without drama.",
        "Collaborative culture screen for mid-level SWE.",
        "Tell me about a time you disagreed with a teammate’s approach on a PR. How did it resolve?",
        [
          "Disagree on the idea, not the person.",
          "Bring data: latency, complexity, rollback risk.",
          "Propose a spike or time-boxed experiment if stuck.",
          "Escalate with a shared decision record if needed.",
          "Own the outcome after the decision — no quiet sabotage.",
        ],
        d(
          "Healthy PR conflict looks like:",
          [
            "Merging your branch in secret",
            "Evidence-based debate and a clear decision",
            "Never reviewing each other’s code again",
            "CC’ing the CEO on every comment",
          ],
          1,
          "Teams hire for disagreement skills under pressure.",
        ),
      ),
      q(
        "url-shortener",
        "System design",
        "URL shortener",
        30,
        "Classic design: write path, read path, scale.",
        "Backend SWE. Expect capacity estimates and uniqueness.",
        "How would you design a URL shortener like bit.ly, covering create, redirect, and scale to high-QPS reads?",
        [
          "Requirements: custom aliases? expiry? analytics?",
          "Write path: generate unique code, store mapping.",
          "Read path: cache hot redirects; handle collisions.",
          "Estimate QPS and storage; shard if needed.",
          "Abuse: rate limits, malware checks.",
        ],
        d(
          "Redirects at scale usually need:",
          [
            "A full table scan on every click",
            "A fast lookup path plus caching for hot keys",
            "Emailing the long URL to the user",
            "Storing passwords next to the mapping",
          ],
          1,
          "Reads dominate; cache and keyed lookups matter.",
        ),
      ),
      q(
        "mentorship",
        "Behavioral",
        "Helping a junior unblock",
        12,
        "Teaching and leverage without taking over.",
        "Senioring signal even for mid-level openings.",
        "Describe a time you helped a less experienced engineer ship. What did you do vs what did they do?",
        [
          "Diagnose the stuck point: skills, context, or confidence.",
          "Teach the fishing rod: pair briefly, then let them drive.",
          "Set a check-in so they aren’t abandoned.",
          "Celebrate their ownership in the write-up.",
          "Reflect what you’d systematize (docs, templates).",
        ],
        d(
          "Strong mentorship stories emphasize:",
          [
            "You did all the coding for them",
            "They retained ownership while you unblocked skillfully",
            "You publicly criticized their pace",
            "You avoided helping to “build character”",
          ],
          1,
          "Leverage without stealing the wheel.",
        ),
      ),
      q(
        "why-us",
        "Closing",
        "Why this engineering team",
        10,
        "Motivation matched to their product and stack.",
        "Final round with hiring manager for product engineering.",
        "Why do you want this role on our team specifically — not just any SWE job?",
        [
          "Tie to their product problem and users.",
          "Name one technical challenge you saw in the JD or blog.",
          "Connect a past project to how you’d contribute in 90 days.",
          "Ask a sharp question that shows you’ve researched.",
          "Avoid generic “I love coding” only.",
        ],
        d(
          "The weakest closing answer is usually:",
          [
            "A specific product + technical hook",
            "Vague praise with no company detail",
            "A 90-day contribution sketch",
            "A thoughtful question back",
          ],
          1,
          "Specificity signals real interest.",
        ),
      ),
    ],
  },
  {
    slug: "product-manager",
    role: "Product Manager",
    setting: "B2B SaaS growth stage",
    blurb: "Prioritization, stakeholders, metrics, and product sense.",
    scenarios: [
      q(
        "priority-conflict",
        "Behavioral",
        "Sales vs engineering",
        12,
        "Deal pressure vs roadmap integrity.",
        "B2B PM interview. Custom ask vs six-week eng cost.",
        "Sales says a $200k deal needs an off-roadmap feature. Eng says six weeks. How do you decide?",
        [
          "Separate customer problem from requested solution.",
          "True cost: build, maintain, opportunity cost.",
          "Reversible options: config, services, timeline trade.",
          "Decide with ICP / retention / strategy criteria.",
          "Same story to Sales and Eng.",
        ],
        d(
          "Strongest PM move:",
          [
            "Always say yes to revenue",
            "Judge problem, cost, and strategic fit — then decide",
            "Hide the ask from engineering",
            "Let Sales own the roadmap",
          ],
          1,
          "Criteria beat the loudest voice.",
        ),
      ),
      q(
        "metric-move",
        "Product sense",
        "Activation is flat",
        20,
        "Diagnose a metric before proposing features.",
        "Growth PM loop. Activation stalled after signup.",
        "Signup→activation dropped 15% MoM. How would you investigate and what might you try?",
        [
          "Define activation precisely; segment by cohort/channel.",
          "Funnel: where the drop happens.",
          "Hypotheses: onboarding, performance, messaging, mix shift.",
          "Prioritize experiments by impact/confidence/effort.",
          "Instrument success before shipping guesses.",
        ],
        d(
          "First step when a metric moves:",
          [
            "Ship three new features immediately",
            "Define the metric and localize the drop",
            "Fire the growth team",
            "Ignore seasonality forever",
          ],
          1,
          "Diagnosis before solution theater.",
        ),
      ),
      q(
        "roadmap-tradeoff",
        "Case",
        "Two big bets, one quarter",
        25,
        "Forced prioritization with incomplete data.",
        "Director-level PM panel. Platform reliability vs new upsell SKU.",
        "You can fund either reliability work that cuts incidents 40% or a new SKU Sales wants. How do you choose?",
        [
          "Clarify goals for the quarter and company stage.",
          "Quantify downside of incidents vs upside of SKU.",
          "Check sequencing: can a thin slice of both work?",
          "Stakeholder map: who blocks, who needs a win.",
          "Recommend with explicit what you won’t do.",
        ],
        d(
          "A good tradeoff answer includes:",
          [
            "Choosing randomly",
            "Explicit criteria and what you deprioritize",
            "Promising both with no cut",
            "Only quoting competitor blogs",
          ],
          1,
          "Prioritization is saying no out loud.",
        ),
      ),
      q(
        "bad-launch",
        "Behavioral",
        "Feature nobody used",
        12,
        "Learning from a failed launch.",
        "PM screen about humility and iteration.",
        "Tell me about a feature that flopped. What did you miss and what changed afterward?",
        [
          "Own the miss: hypothesis that failed.",
          "Evidence: usage, qualitative feedback.",
          "What you’d validate earlier next time.",
          "How you sunsets or iterated.",
          "Process change: research, kill criteria, instrumentation.",
        ],
        d(
          "Interviewers want:",
          [
            "Blame on design only",
            "Clear learning and a changed habit",
            "Denial that it flopped",
            "A pivot to unrelated achievements",
          ],
          1,
          "Reflection beats perfection.",
        ),
      ),
      q(
        "pricing-question",
        "Product sense",
        "Should we add a free tier",
        20,
        "Business model judgment.",
        "PLG-curious B2B company interviewing PMs.",
        "Should we add a free tier? How would you think about it?",
        [
          "Goal: acquisition, expansion, or competitive response?",
          "Unit economics: cost to serve free users.",
          "Conversion path and time-to-value.",
          "Risks: support load, cannibalization.",
          "Test design: geo or cohort experiment if possible.",
        ],
        d(
          "Free-tier decisions hinge on:",
          [
            "Only what competitors do",
            "Goals, cost to serve, and conversion path",
            "Designer preference for empty states",
            "CEO’s favorite color",
          ],
          1,
          "Strategy + economics, not copycat features.",
        ),
      ),
      q(
        "exec-update",
        "Communication",
        "Bad news to leadership",
        10,
        "Crisp status under pressure.",
        "PM role with heavy exec visibility.",
        "Your key launch slips two weeks. How do you update leadership?",
        [
          "Lead with outcome and new date.",
          "Root cause in one sentence, not a novel.",
          "Options with tradeoffs; recommend one.",
          "Risks remaining and asks you need.",
          "No surprise: if you knew earlier, say when.",
        ],
        d(
          "Best exec updates:",
          [
            "Hide the slip until demo day",
            "Outcome, cause, options, ask — briefly",
            "Forward 40 Slack threads",
            "Blame a single IC by name",
          ],
          1,
          "Clarity builds trust when news is bad.",
        ),
      ),
      q(
        "user-research",
        "Product sense",
        "Conflicting user feedback",
        15,
        "Synthesize noisy qualitative input.",
        "Consumer/SMB PM interview.",
        "Power users want complexity; new users want simplicity. How do you decide the next UX bet?",
        [
          "Segment: who drives retention/revenue.",
          "Jobs-to-be-done vs feature requests.",
          "Look for progressive disclosure patterns.",
          "Validate with a prototype or A/B.",
          "Write the decision principle you’ll reuse.",
        ],
        d(
          "When users conflict, prioritize by:",
          [
            "Whoever emailed last",
            "Segment impact and job-to-be-done evidence",
            "Adding every request",
            "Ignoring new users forever",
          ],
          1,
          "Segments + jobs beat inbox democracy.",
        ),
      ),
      q(
        "tech-debt",
        "Case",
        "Eng wants a rewrite",
        18,
        "Partnering on debt without losing product outcomes.",
        "PM working with a platform team.",
        "Engineering proposes a three-month rewrite of the billing service. How do you evaluate?",
        [
          "Problem: incidents, velocity, cost to change?",
          "Alternatives: strangler, targeted refactors.",
          "Product risk of pause vs risk of status quo.",
          "Milestones that deliver intermediate value.",
          "Success metrics for the rewrite itself.",
        ],
        d(
          "Evaluate a rewrite by:",
          [
            "Approving because rewrites are cool",
            "Problem severity, alternatives, and incremental value",
            "Rejecting all eng proposals",
            "Only asking Sales",
          ],
          1,
          "Outcomes and risk, not ideology.",
        ),
      ),
      q(
        "competitor",
        "Product sense",
        "Competitor shipped your idea",
        12,
        "Competitive response without panic.",
        "Category with noisy competitors.",
        "A competitor just launched a feature you planned for next quarter. What do you do?",
        [
          "Don’t mirror blindly — check differentiation.",
          "Talk to customers: do they care?",
          "Assess build vs partner vs ignore.",
          "Adjust messaging if perception risk is high.",
          "Protect strategy; avoid feature whack-a-mole.",
        ],
        d(
          "Best first reaction:",
          [
            "Ship a clone by Friday",
            "Validate customer impact before changing the plan",
            "Publicly attack the competitor",
            "Cancel the roadmap entirely",
          ],
          1,
          "Customer evidence over competitor FOMO.",
        ),
      ),
      q(
        "why-pm",
        "Closing",
        "Why product here",
        10,
        "Motivation and 90-day plan.",
        "Hiring manager close for PM.",
        "Why this PM role, and what would your first 90 days look like?",
        [
          "Connect to their users and business model.",
          "Show you’ve used or studied the product.",
          "90 days: learn, ship a small win, build trust.",
          "Name stakeholders you’d interview first.",
          "Ask what success looks like at month three.",
        ],
        d(
          "A strong close includes:",
          [
            "Only salary questions",
            "Specific product hook plus a grounded 90-day sketch",
            "Criticizing their current PM",
            "Refusing to discuss priorities",
          ],
          1,
          "Curiosity + concrete plan.",
        ),
      ),
    ],
  },
  {
    slug: "data-analyst",
    role: "Data Analyst",
    setting: "Multi-sided marketplace",
    blurb: "Metrics debates, SQL, experiments, and stakeholder storytelling.",
    scenarios: [
      q(
        "metric-disagreement",
        "Behavioral",
        "Two dashboards, two truths",
        12,
        "Reconcile conflicting numbers.",
        "Analyst interview with noisy self-serve BI.",
        "Growth and Finance show different revenue numbers. How do you reconcile?",
        [
          "Definitions: booking vs recognized, gross vs net.",
          "Timezones, filters, delayed events.",
          "Trace to source tables with a small sample.",
          "Document the canonical metric.",
          "Communicate the fix without blaming teams.",
        ],
        d(
          "First move in a metric fight:",
          [
            "Pick the higher number",
            "Align definitions and lineage",
            "Delete both dashboards",
            "Average the two numbers",
          ],
          1,
          "Definitions before drama.",
        ),
      ),
      q(
        "sql-funnel",
        "Technical",
        "Build a signup funnel",
        20,
        "SQL for stepwise conversion.",
        "Live SQL screen for product analytics.",
        "How would you write SQL (or describe it) for signup → verify email → first action conversion by week?",
        [
          "Clarify event names and uniqueness.",
          "Cohort by signup week.",
          "Step events with first-touch timestamps.",
          "Watch for duplicates and bots.",
          "Output rates plus absolute counts.",
        ],
        d(
          "Funnel SQL should usually:",
          [
            "Count page views only once ever",
            "Cohort users and measure ordered step completion",
            "Ignore time windows",
            "Join every table in the warehouse",
          ],
          1,
          "Cohorts + ordered steps = a funnel.",
        ),
      ),
      q(
        "experiment-readout",
        "Case",
        "A/B test is “mixed”",
        18,
        "Nuanced experiment interpretation.",
        "Experimentation-mature product team.",
        "Treatment lifts clicks 8% but revenue is flat. What do you tell the PM?",
        [
          "Check novelty, sample ratio, segments.",
          "Primary metric vs guardrails.",
          "Practical significance vs statistical.",
          "Hypotheses for click≠revenue.",
          "Recommend ship / iterate / kill with rationale.",
        ],
        d(
          "When secondary lifts but primary doesn’t:",
          [
            "Always ship for the vanity metric",
            "Explain tradeoffs against the decision metric",
            "Hide the flat revenue",
            "Rerun forever with no learning",
          ],
          1,
          "Decision metric stays the north star.",
        ),
      ),
      q(
        "messy-data",
        "Behavioral",
        "Garbage in, deadline out",
        12,
        "Data quality under time pressure.",
        "Ops-heavy analyst role.",
        "You’re asked for a board metric tomorrow but the source table has known null spikes. What do you do?",
        [
          "Quantify the quality issue’s impact.",
          "Offer a provisional number with caveats.",
          "Propose a quick validation sample.",
          "Escalate if the number could mislead capital decisions.",
          "File a durable fix after the deadline.",
        ],
        d(
          "Best practice under a bad-data deadline:",
          [
            "Ship a fake precise number",
            "Caveated estimate plus quality callout",
            "Refuse all communication",
            "Wait silently past the meeting",
          ],
          1,
          "Honesty with bounds beats false precision.",
        ),
      ),
      q(
        "cohort-retention",
        "Technical",
        "Retention curves",
        15,
        "Explain retention to a non-technical stakeholder.",
        "Consumer subscription company.",
        "Explain how you’d measure Day-1 / Day-7 / Day-30 retention and what would worry you?",
        [
          "Define the activating event and return event.",
          "Cohort by first use date.",
          "Plot curves; watch for mix shifts.",
          "Segment by channel or plan.",
          "Watch out for timezone and resurfacing bots.",
        ],
        d(
          "Retention analysis starts with:",
          [
            "A single lifetime average only",
            "Clear cohort definition and return event",
            "Ignoring new user mix",
            "Only NPS",
          ],
          1,
          "Cohorts make retention comparable.",
        ),
      ),
      q(
        "stakeholder-pushback",
        "Behavioral",
        "Leader wants a different chart",
        10,
        "Integrity when asked to “make it look better.”",
        "Analyst supporting an exec team.",
        "A director asks you to exclude a segment so the chart looks greener. How do you respond?",
        [
          "Seek the decision they’re trying to make.",
          "Offer transparent cuts labeled as scenario analysis.",
          "Refuse silent exclusion of inconvenient data.",
          "Escalate if pressured to mislead.",
          "Propose the honest narrative that still helps action.",
        ],
        d(
          "Ethical response is:",
          [
            "Quietly exclude the segment",
            "Transparent analysis — no silent cherry-picking",
            "Leak the chart to Twitter",
            "Quit mid-meeting",
          ],
          1,
          "Credibility is the analyst’s product.",
        ),
      ),
      q(
        "forecast",
        "Case",
        "Rough forecast in an hour",
        15,
        "Pragmatic forecasting under uncertainty.",
        "Bizops-adjacent analyst interview.",
        "Leadership wants next-quarter active users in an hour. Approach?",
        [
          "Ask what decision the forecast drives.",
          "Simple baseline: trailing growth + seasonality.",
          "Sensitivity: low/base/high.",
          "Call out assumptions explicitly.",
          "Offer a follow-up with a better model.",
        ],
        d(
          "Fast forecasts should include:",
          [
            "A single fake decimal precision",
            "Assumptions and a range",
            "No baseline",
            "Only ML buzzwords",
          ],
          1,
          "Ranges + assumptions beat false precision.",
        ),
      ),
      q(
        "dashboard-design",
        "Product sense",
        "Design a weekly exec dashboard",
        15,
        "Less is more for decision makers.",
        "Analytics platform team hiring analysts who think like PMs.",
        "Design a one-page weekly dashboard for the CEO. What makes the cut?",
        [
          "North-star + 3–5 input metrics.",
          "Trends vs targets, not raw dumps.",
          "Annotations for known incidents.",
          "Links to deeper cuts for owners.",
          "Kill vanity metrics without decisions.",
        ],
        d(
          "Exec dashboards fail when they:",
          [
            "Focus on decisions",
            "Show dozens of unprioritized charts",
            "Highlight targets",
            "Annotate anomalies",
          ],
          1,
          "Attention is the scarce resource.",
        ),
      ),
      q(
        "causal-vs-corr",
        "Technical",
        "Correlation trap",
        12,
        "Causal reasoning in product analytics.",
        "Experiment-literate org.",
        "Marketing says “users who see ads convert more — ads work.” How do you respond?",
        [
          "Selection bias: who sees ads?",
          "Propose experiment or quasi-experiment.",
          "Check confounders: intent, geography.",
          "Offer incremental lift framing.",
          "Educate without dunking on Marketing.",
        ],
        d(
          "Strongest reply to “ads users convert more”:",
          [
            "Agree without checking bias",
            "Call out selection bias and seek incremental evidence",
            "Ban all ads",
            "Only quote a TED talk",
          ],
          1,
          "Incrementality > correlation stories.",
        ),
      ),
      q(
        "why-analyst",
        "Closing",
        "Why this analytics team",
        8,
        "Motivation and craft.",
        "Hiring manager close.",
        "Why analytics here, and what problem are you excited to tackle first?",
        [
          "Reference their product’s data challenge.",
          "Show a past analysis style that transfers.",
          "Name a first problem you’d explore.",
          "Ask how decisions currently use data.",
          "Avoid “I like Excel” as the whole answer.",
        ],
        d(
          "Strong closes are:",
          [
            "Generic love of numbers only",
            "Specific product problem + transferable craft",
            "Salary-only discussion",
            "Critiques with no curiosity",
          ],
          1,
          "Specificity wins.",
        ),
      ),
    ],
  },
  {
    slug: "marketing",
    role: "Marketing",
    setting: "Consumer subscription brand",
    blurb: "Budget tradeoffs, channels, crises, and creative judgment.",
    scenarios: [
      q(
        "budget-cut",
        "Case",
        "20% budget cut",
        15,
        "Prioritize channels under constraint.",
        "Growth marketing interview mid-year.",
        "You must cut paid budget 20% next month. How do you decide what stays?",
        [
          "Rank by efficient growth and strategic learning.",
          "Protect brand-critical moments if needed.",
          "Cut lowest marginal CAC / weak creative.",
          "Communicate tradeoffs to Sales/Product.",
          "Set a review date to restore spend.",
        ],
        d(
          "Budget cuts should prioritize:",
          [
            "Equal cuts everywhere",
            "Marginal efficiency and strategic must-keeps",
            "Only the CEO’s favorite channel",
            "Cutting measurement first",
          ],
          1,
          "Efficiency + strategy, not peanut-butter cuts.",
        ),
      ),
      q(
        "channel-choice",
        "Case",
        "Launch channel bet",
        18,
        "Pick a primary acquisition channel.",
        "New product launch with limited creative capacity.",
        "We’re launching in two cities. Pick one primary paid channel and justify?",
        [
          "Audience fit and intent.",
          "Creative format strengths.",
          "Learning speed and measurement.",
          "Competitive clutter.",
          "Test plan with kill criteria.",
        ],
        d(
          "Channel choice should hinge on:",
          [
            "Whatever is trending on TikTok alone",
            "Audience fit, measurement, and learning speed",
            "The agency’s retainer size",
            "Ignoring creative constraints",
          ],
          1,
          "Fit + learnability beat hype.",
        ),
      ),
      q(
        "crisis-post",
        "Behavioral",
        "Public complaint goes viral",
        12,
        "Comms under scrutiny.",
        "Brand/social role overlapping lifecycle marketing.",
        "A customer’s complaint about billing goes viral. What’s your first hour?",
        [
          "Verify facts with Support/Legal.",
          "Respond with empathy and a path to resolution.",
          "Don’t argue publicly point-by-point.",
          "Align internal owners on the fix.",
          "Follow up when resolved; capture learning.",
        ],
        d(
          "First hour priority:",
          [
            "Joke about the customer",
            "Verify facts, empathize, route to resolution",
            "Delete all comments",
            "Post a meme",
          ],
          1,
          "Empathy + facts beat ego.",
        ),
      ),
      q(
        "campaign-postmortem",
        "Behavioral",
        "Campaign missed target",
        12,
        "Learning from underperformance.",
        "Performance marketing screen.",
        "Your last campaign missed CPA by 30%. Walk me through the postmortem?",
        [
          "Results vs plan, plainly.",
          "Diagnose: audience, creative, landing, tracking.",
          "What you’d test next.",
          "What you’d stop doing.",
          "Share learnings with the team.",
        ],
        d(
          "Good postmortems:",
          [
            "Blame the algorithm only",
            "Specific diagnosis and next tests",
            "Hide the miss",
            "Fire the designer immediately",
          ],
          1,
          "Learning loops are the job.",
        ),
      ),
      q(
        "positioning",
        "Case",
        "Rewrite the homepage promise",
        15,
        "Positioning clarity.",
        "Product marketing interview.",
        "Our homepage says five different things. How would you land one promise?",
        [
          "Who is the primary ICP?",
          "Job-to-be-done and alternatives.",
          "Proof points you can actually claim.",
          "Test 2–3 messaging variants.",
          "Align Paid/Sales/CS on the same line.",
        ],
        d(
          "Positioning starts with:",
          [
            "More buzzwords",
            "ICP + job + proof",
            "Copying a competitor headline",
            "Listing every feature",
          ],
          1,
          "Clarity for one buyer beats kitchen-sink copy.",
        ),
      ),
      q(
        "influencer",
        "Case",
        "Influencer deal ROI",
        12,
        "Evaluate partnership economics.",
        "Creator-led growth brand.",
        "An influencer wants $25k for one post. How do you evaluate?",
        [
          "Audience overlap and authenticity fit.",
          "Expected reach → conversion assumptions.",
          "Tracking: codes, UTMs, lift tests.",
          "Rights and whitelisting value.",
          "Walk-away number and alternatives.",
        ],
        d(
          "Judge influencer deals by:",
          [
            "Follower count alone",
            "Fit, tracked conversion assumptions, and rights value",
            "How famous their dog is",
            "Paying whatever they ask",
          ],
          1,
          "Economics + fit, not vanity reach.",
        ),
      ),
      q(
        "email-lifecycle",
        "Technical",
        "Fix onboarding email",
        12,
        "Lifecycle craft.",
        "CRM/lifecycle marketing role.",
        "Day-1 email has 60% open but 1% click. What do you change?",
        [
          "Audit promise in subject vs body CTA.",
          "Simplify to one primary action.",
          "Segment by intent/source.",
          "Test placement and copy.",
          "Check deliverability and rendering.",
        ],
        d(
          "High open / low click usually means:",
          [
            "Subject works but body CTA is weak or unclear",
            "You need more GIFs only",
            "Abandon email forever",
            "Buy a bigger ESP logo",
          ],
          0,
          "Align promise and action.",
        ),
      ),
      q(
        "brand-vs-perf",
        "Case",
        "Brand vs performance split",
        15,
        "Portfolio thinking.",
        "Marketing lead interview at a growth-stage company.",
        "How would you split budget between brand and performance for the next two quarters?",
        [
          "Company stage and payback goals.",
          "Measurement maturity for brand.",
          "Risk of only harvesting demand.",
          "Propose a testable brand slice.",
          "Review cadence with finance.",
        ],
        d(
          "Split decisions need:",
          [
            "100% whatever is easiest to attribute",
            "Stage, payback, and measurement reality",
            "Ignoring finance",
            "Copying last year’s pie chart",
          ],
          1,
          "Context beats dogma.",
        ),
      ),
      q(
        "cross-functional",
        "Behavioral",
        "Product slipped your launch",
        10,
        "Cross-team resilience.",
        "Integrated campaign planner role.",
        "Product delays a feature your campaign depends on by three weeks. What do you do?",
        [
          "Replan assets and channel bookings.",
          "Find a still-true story to ship.",
          "Protect spend from waste.",
          "Reset expectations with stakeholders.",
          "Capture a better launch checklist.",
        ],
        d(
          "Best response:",
          [
            "Run the ads anyway for a missing feature",
            "Replan messaging and protect wasted spend",
            "Publicly blame Product",
            "Go dark with no notice",
          ],
          1,
          "Adapt without burning cash or trust.",
        ),
      ),
      q(
        "why-marketing",
        "Closing",
        "Why this brand",
        8,
        "Motivation close.",
        "Hiring manager final.",
        "Why this marketing role and brand?",
        [
          "Specific brand/audience insight.",
          "Channel craft you bring.",
          "A 30-day listening plan.",
          "Question about their growth bottleneck.",
          "Avoid generic “I love storytelling” only.",
        ],
        d(
          "Strong closes cite:",
          [
            "Only that the office has snacks",
            "Audience insight + craft you’ll apply",
            "No research",
            "Competitor bashing",
          ],
          1,
          "Show you’ve done the homework.",
        ),
      ),
    ],
  },
  {
    slug: "customer-success",
    role: "Customer Success",
    setting: "B2B mid-market SaaS",
    blurb: "Retention, escalations, QBRs, and expansion judgment.",
    scenarios: [
      q(
        "churn-risk",
        "Case",
        "Logo at risk",
        15,
        "Save plan for a sliding account.",
        "CSM interview for mid-market book.",
        "Usage dropped 40% and a champion left. How do you run the next two weeks?",
        [
          "Map new stakeholders fast.",
          "Diagnose value gap vs product gap.",
          "Executive sponsor outreach if needed.",
          "Time-bound success plan.",
          "Update forecast honestly.",
        ],
        d(
          "First focus on a churn risk:",
          [
            "Ignore until renewal week",
            "Re-establish stakeholders and a dated success plan",
            "Discount immediately with no diagnosis",
            "Only send a NPS survey",
          ],
          1,
          "People + plan beat panic discounts.",
        ),
      ),
      q(
        "escalation-call",
        "Behavioral",
        "Angry executive call",
        12,
        "De-escalate while owning outcomes.",
        "Enterprise CS motion.",
        "A VP joins a call furious about a bug. How do you run the conversation?",
        [
          "Listen fully; mirror the impact.",
          "Separate emotion from facts.",
          "Commit only what you can deliver.",
          "Bring Eng/Support with a clear owner.",
          "Follow up in writing same day.",
        ],
        d(
          "On an angry exec call, do not:",
          [
            "Empathize and commit realistically",
            "Argue about their tone",
            "Bring the right technical owner",
            "Send a written follow-up",
          ],
          1,
          "Tone fights escalate; ownership calms.",
        ),
      ),
      q(
        "qbr-story",
        "Case",
        "QBR without clear ROI",
        18,
        "Structure a QBR that earns renewal.",
        "CS interview mid-market.",
        "Customer says they can’t see ROI in the QBR. How do you structure the meeting?",
        [
          "Start from their goals.",
          "2–3 usage insights tied to outcomes.",
          "Admit gaps; 30-day value plan.",
          "Define “ROI proven” in their words.",
          "Dated next steps, not slideware.",
        ],
        d(
          "QBRs without ROI should emphasize:",
          [
            "More screenshots",
            "Goals, honest gaps, dated value plan",
            "Only NPS",
            "Competitor bashing",
          ],
          1,
          "Mutual planning > product tours.",
        ),
      ),
      q(
        "expansion",
        "Case",
        "Upsell without being salesy",
        12,
        "Expansion from value, not pressure.",
        "CS + commercial hybrid role.",
        "You see an expansion opportunity. How do you approach without damaging trust?",
        [
          "Evidence of value already delivered.",
          "Tie upsell to a job they’re failing today.",
          "Multi-thread; don’t surprise procurement.",
          "Partner with AE on commercial steps.",
          "Accept no without punishing support quality.",
        ],
        d(
          "Healthy expansion starts from:",
          [
            "Threats about support",
            "Proven value and a clear new job-to-be-done",
            "Blind discounting",
            "Ignoring the AE",
          ],
          1,
          "Trust funds expansion.",
        ),
      ),
      q(
        "onboarding",
        "Case",
        "Slow time-to-value",
        15,
        "Fix onboarding for a new logo.",
        "Implementation-heavy CS role.",
        "New customer hasn’t hit first value in 45 days. What’s your plan?",
        [
          "Redefine first value milestone with them.",
          "Remove blockers: data, access, training.",
          "Weekly cadence with clear owners.",
          "Escalate internally if product gaps.",
          "Reset success criteria if needed.",
        ],
        d(
          "Slow TTV needs:",
          [
            "Waiting until renewal",
            "A shared milestone plan and blocker removal",
            "More feature emails only",
            "Ghosting the account",
          ],
          1,
          "Shared milestones unlock momentum.",
        ),
      ),
      q(
        "feature-request",
        "Behavioral",
        "Customer demands a custom feature",
        10,
        "Advocacy without false promises.",
        "CS at a product-led roadmap company.",
        "A strategic account demands a custom feature. How do you handle it?",
        [
          "Capture the underlying job.",
          "Don’t promise roadmap dates you don’t own.",
          "Workarounds and timeline honesty.",
          "Feed Product with evidence and urgency.",
          "Keep the relationship warm either way.",
        ],
        d(
          "Never:",
          [
            "Capture the job-to-be-done",
            "Invent a ship date you can’t control",
            "Offer workarounds",
            "Loop in Product with evidence",
          ],
          1,
          "False dates destroy trust.",
        ),
      ),
      q(
        "health-score",
        "Technical",
        "Design an account health score",
        15,
        "Operationalize risk detection.",
        "CS ops / CSM hybrid interview.",
        "What inputs would you use for an account health score, and how would CS act on it?",
        [
          "Usage, support severity, stakeholder coverage.",
          "Outcomes progress vs goals.",
          "Avoid vanity-only signals.",
          "Playbooks by risk tier.",
          "Review false positives with the team.",
        ],
        d(
          "Health scores should drive:",
          [
            "A pretty chart only",
            "Tiered playbooks and human judgment",
            "Automatic account cancellation",
            "Public shaming of CSMs",
          ],
          1,
          "Scores without actions are decoration.",
        ),
      ),
      q(
        "internal-conflict",
        "Behavioral",
        "Support vs Product finger-pointing",
        12,
        "Cross-functional diplomacy.",
        "CSM stuck between orgs.",
        "Support says it’s a product bug; Product says user error. Customer is waiting. What do you do?",
        [
          "Reproduce with evidence.",
          "Facilitate a joint triage, not a Slack war.",
          "Give customer interim guidance.",
          "Document decision and owner.",
          "Fix the recurring process gap.",
        ],
        d(
          "Your job in the middle is to:",
          [
            "Pick a side publicly",
            "Drive evidence-based triage and customer updates",
            "Forward angry emails only",
            "Stop answering the customer",
          ],
          1,
          "CS owns the customer experience of the conflict.",
        ),
      ),
      q(
        "renewal-forecast",
        "Case",
        "Commit the forecast",
        12,
        "Honest forecasting.",
        "CS leader screen for pipeline hygiene.",
        "How do you decide commit vs upside vs at-risk for renewals?",
        [
          "Evidence: champion strength, value proof, competitors.",
          "Commercial signals: legal, budget timing.",
          "Write the risks explicitly.",
          "Update when facts change — no sandbag surprises.",
          "Separate hope from commit.",
        ],
        d(
          "Commit should mean:",
          [
            "Wishful thinking",
            "Evidence-backed likelihood you’d bet your name on",
            "Every logo in the book",
            "Whatever Finance wants to hear",
          ],
          1,
          "Forecast integrity is a CS skill.",
        ),
      ),
      q(
        "why-cs",
        "Closing",
        "Why customer success here",
        8,
        "Motivation close.",
        "Hiring manager final.",
        "Why CS at this company, and what does great look like at day 90?",
        [
          "Customer segment you’re drawn to.",
          "Retention lever you want to own.",
          "90-day: book fluency, early saves, trust.",
          "Ask how they measure CSM success.",
          "Avoid “I’m a people person” as the whole pitch.",
        ],
        d(
          "Strong CS closes include:",
          [
            "Only soft-skills clichés",
            "Segment insight + concrete 90-day outcomes",
            "No questions",
            "Criticizing Support",
          ],
          1,
          "Outcomes > vibes.",
        ),
      ),
    ],
  },
  {
    slug: "ux-designer",
    role: "UX Designer",
    setting: "Product design team at a fintech",
    blurb: "Critique, research, tradeoffs, and stakeholder storytelling.",
    scenarios: [
      q(
        "design-critique",
        "Portfolio",
        "Walk a portfolio critique",
        20,
        "How you receive and give feedback.",
        "Product design interview with a live critique.",
        "I’ll critique this screen. How do you usually run a critique, and how do you respond to tough feedback?",
        [
          "Separate goals from aesthetics.",
          "Ask clarifying questions before defending.",
          "Take notes; decide what to change.",
          "Give feedback that’s actionable and kind.",
          "Show a revision that reflects learning.",
        ],
        d(
          "Strong critique behavior:",
          [
            "Defend every pixel immediately",
            "Clarify goals, listen, revise deliberately",
            "Ignore feedback entirely",
            "Only compliment others",
          ],
          1,
          "Growth mindset is visible in critique.",
        ),
      ),
      q(
        "research-plan",
        "Case",
        "Usability study in a week",
        15,
        "Right-sized research.",
        "UX role with light research support.",
        "You have one week before eng locks scope. How do you research a checkout redesign?",
        [
          "Prioritize riskiest assumptions.",
          "5–7 targeted sessions or unmoderated tests.",
          "Prototype fidelity matched to questions.",
          "Synthesize into decisions, not a 40-page deck.",
          "Call out what you still don’t know.",
        ],
        d(
          "Tight timelines favor:",
          [
            "A six-month ethnography only",
            "Focused tests on riskiest assumptions",
            "Skipping users entirely",
            "Surveys with no task observation",
          ],
          1,
          "Risk-based research beats ritual research.",
        ),
      ),
      q(
        "accessibility",
        "Technical",
        "Accessibility miss in review",
        12,
        "A11y as a design requirement.",
        "Fintech with compliance pressure.",
        "Eng flags that your flow fails keyboard navigation. How do you respond?",
        [
          "Treat a11y as a defect, not polish.",
          "Reproduce with keyboard/screen reader.",
          "Fix patterns in the design system if systemic.",
          "Add acceptance checks to the handoff.",
          "Thank the catch; don’t get defensive.",
        ],
        d(
          "Accessibility issues are:",
          [
            "Nice-to-haves for later",
            "Product quality requirements",
            "Only legal’s problem",
            "Solved by color alone",
          ],
          1,
          "Inclusive design is core quality.",
        ),
      ),
      q(
        "pm-conflict",
        "Behavioral",
        "PM wants more on the page",
        12,
        "Advocate for users without blocking shipping.",
        "Collaborative product triad interview.",
        "PM wants three CTAs above the fold. You think it hurts conversion. What do you do?",
        [
          "Reframe around the user job and metrics.",
          "Show evidence or propose a quick test.",
          "Offer a compromise layout.",
          "Disagree and commit if leadership decides.",
          "Document the decision for later learning.",
        ],
        d(
          "Healthy pushback uses:",
          [
            "“Because I said so”",
            "User goals, evidence, and testable alternatives",
            "Silent resistance after agreeing",
            "Designing in a vacuum",
          ],
          1,
          "Influence with evidence.",
        ),
      ),
      q(
        "design-system",
        "Case",
        "Break the system or bend it",
        15,
        "System thinking vs one-off UI.",
        "Design systems mature org.",
        "A marketing landing needs a pattern not in the system. Ship a one-off or extend the system?",
        [
          "Frequency and reuse potential.",
          "Cost to maintain one-offs.",
          "Time-to-ship pressure.",
          "Propose a temporary exception with expiry.",
          "If extending, define API and accessibility.",
        ],
        d(
          "Decide based on:",
          [
            "Always one-off forever",
            "Reuse, maintenance cost, and urgency",
            "Never ship marketing pages",
            "Only what Figma Community has",
          ],
          1,
          "Systems need intentional exceptions.",
        ),
      ),
      q(
        "metrics-design",
        "Case",
        "Did the redesign work",
        12,
        "Outcome-minded design.",
        "Growth-aware design team.",
        "How would you know if a navigation redesign succeeded?",
        [
          "Define success metrics up front.",
          "Task success / time-on-task / support tickets.",
          "Segment new vs returning users.",
          "Qual follow-ups for confusion.",
          "Avoid vanity aesthetic scores alone.",
        ],
        d(
          "Success should include:",
          [
            "Only “stakeholders liked the colors”",
            "Behavioral metrics tied to user jobs",
            "Ignoring support volume",
            "No baseline",
          ],
          1,
          "Design quality shows in behavior.",
        ),
      ),
      q(
        "handoff",
        "Technical",
        "Eng says specs are unclear",
        10,
        "Handoff craft.",
        "Maker team with fast sprints.",
        "Engineers say your specs are ambiguous. How do you improve handoff?",
        [
          "States: empty, loading, error, edge.",
          "Interaction notes and accessibility.",
          "Office hours / pairing on complex flows.",
          "Shared component references.",
          "Ask what ambiguity cost them last time.",
        ],
        d(
          "Clear handoffs cover:",
          [
            "Happy path screenshots only",
            "States, interactions, and edge cases",
            "No conversation with eng",
            "PDF posters only",
          ],
          1,
          "Ambiguity becomes bugs.",
        ),
      ),
      q(
        "ethical-design",
        "Behavioral",
        "Dark pattern request",
        12,
        "Ethics under business pressure.",
        "Fintech trust-sensitive product.",
        "Growth asks for a confirmshaming cancel flow. How do you handle it?",
        [
          "Name the user harm and trust risk.",
          "Propose ethical alternatives that still retain.",
          "Escalate with principles if needed.",
          "Document the decision.",
          "Don’t silently implement harm.",
        ],
        d(
          "Best response to dark patterns:",
          [
            "Ship because Growth asked",
            "Refuse harm; offer ethical retention alternatives",
            "Ignore the request with no reply",
            "Publicly shame Growth on social",
          ],
          1,
          "Trust is a product requirement.",
        ),
      ),
      q(
        "mobile-constraint",
        "Case",
        "Desktop design on mobile",
        15,
        "Constraint-driven redesign.",
        "Multi-platform product.",
        "Your desktop-dense dashboard must work on mobile. Approach?",
        [
          "Prioritize primary jobs for small screens.",
          "Progressive disclosure.",
          "Touch targets and performance.",
          "Don’t shrink everything 1:1.",
          "Validate with real devices.",
        ],
        d(
          "Mobile adaptation should:",
          [
            "Shrink the desktop UI uniformly",
            "Re-prioritize jobs for the context",
            "Drop accessibility",
            "Ignore performance",
          ],
          1,
          "Context rewrite > scale transform.",
        ),
      ),
      q(
        "why-design",
        "Closing",
        "Why this design team",
        8,
        "Motivation close.",
        "Design manager final.",
        "Why this UX role, and how do you want to grow here?",
        [
          "Product domain interest (fintech users).",
          "Craft area you want to deepen.",
          "How you partner with PM/Eng.",
          "Ask about design’s seat in decisions.",
          "Avoid portfolio tour as the only answer.",
        ],
        d(
          "Strong closes connect:",
          [
            "Only aesthetic preferences",
            "Domain + craft growth + collaboration style",
            "No questions about the team",
            "Competitor portfolio dunks",
          ],
          1,
          "Show how you’ll work, not only what you’ve drawn.",
        ),
      ),
    ],
  },
  {
    slug: "account-executive",
    role: "Account Executive",
    setting: "B2B enterprise sales",
    blurb: "Discovery, deals, objections, and forecast discipline.",
    scenarios: [
      q(
        "discovery-call",
        "Role play",
        "Run discovery",
        20,
        "Questions over pitch.",
        "AE interview with a mock discovery.",
        "You’re on a first call with a VP Ops. How do you run discovery in 20 minutes?",
        [
          "Goal and current process first.",
          "Pain, impact, urgency.",
          "Stakeholders and buying process.",
          "Qualify fit honestly.",
          "Agree a next step with mutual value.",
        ],
        d(
          "Discovery fails when you:",
          [
            "Ask about pain and process",
            "Pitch slides for 18 minutes",
            "Map stakeholders",
            "Earn a clear next step",
          ],
          1,
          "Ears before decks.",
        ),
      ),
      q(
        "price-objection",
        "Role play",
        "We’re too expensive",
        12,
        "Negotiate on value.",
        "Late-stage enterprise deal.",
        "Buyer says you’re 30% above a competitor. How do you respond?",
        [
          "Clarify what they’re comparing.",
          "Re-anchor on outcomes and risk.",
          "Uncover must-have vs nice-to-have.",
          "Trade, don’t just discount.",
          "Know your walk-away.",
        ],
        d(
          "Best first move on price:",
          [
            "Discount 30% instantly",
            "Clarify comparison and re-anchor on value",
            "Insult the competitor",
            "End the call",
          ],
          1,
          "Understand before you concede.",
        ),
      ),
      q(
        "lost-deal",
        "Behavioral",
        "Deal you lost",
        12,
        "Learning from loss.",
        "AE behavioral screen.",
        "Tell me about a deal you lost. What did you miss?",
        [
          "Own the miss without bitterness.",
          "Was it champion, timing, product, process?",
          "What signal you ignored.",
          "What you changed afterward.",
          "No blaming “bad luck” only.",
        ],
        d(
          "Strong loss stories show:",
          [
            "Only competitor hatred",
            "Diagnosis and a changed behavior",
            "Denial",
            "Blaming legal forever",
          ],
          1,
          "Sellers who learn compound.",
        ),
      ),
      q(
        "multi-thread",
        "Case",
        "Single-threaded deal",
        15,
        "Multi-threading risk.",
        "Enterprise AE loop.",
        "You’re single-threaded with a friendly manager. Economic buyer is invisible. Plan?",
        [
          "Ask for a map of decision makers.",
          "Offer value for the exec (insight, ROI model).",
          "Use mutual action plans.",
          "Risk the deal status in forecast.",
          "Don’t pretend one champion is enough.",
        ],
        d(
          "Single-threading is risky because:",
          [
            "Champions never leave",
            "One contact can block or vanish",
            "Legal loves it",
            "Forecasts get more accurate automatically",
          ],
          1,
          "Access to power is part of the job.",
        ),
      ),
      q(
        "forecast",
        "Case",
        "Sandbag or stretch",
        10,
        "Forecast integrity.",
        "Sales culture interview.",
        "Your manager wants a stretch commit. You think two deals are shaky. What do you do?",
        [
          "Separate commit vs upside clearly.",
          "Evidence for each deal stage.",
          "Don’t lie to make a meeting feel good.",
          "Ask what help would make upside real.",
          "Update when facts change.",
        ],
        d(
          "Forecast trust requires:",
          [
            "Inflating to please",
            "Honest commit vs upside with evidence",
            "Hiding slippage",
            "Only annual numbers",
          ],
          1,
          "Credibility closes more than heroics.",
        ),
      ),
      q(
        "product-gap",
        "Role play",
        "Missing feature in demo",
        12,
        "Honesty under demo pressure.",
        "Solution-selling motion.",
        "Prospect asks for a feature you don’t have mid-demo. Response?",
        [
          "Don’t invent roadmap dates.",
          "Probe the job behind the ask.",
          "Show workarounds or partners.",
          "Bring Product for strategic accounts.",
          "Protect trust over the quarter number.",
        ],
        d(
          "Never:",
          [
            "Probe the underlying job",
            "Invent a ship date",
            "Offer a workaround",
            "Involve Product when strategic",
          ],
          1,
          "Fake dates create worse churn later.",
        ),
      ),
      q(
        "long-cycle",
        "Behavioral",
        "Nine-month deal",
        12,
        "Patience and process.",
        "Enterprise cycle company.",
        "Tell me about a long deal you advanced without forcing a premature close. What happened?",
        [
          "Mutual action plan with dates.",
          "Value at each stage.",
          "Multi-thread continuously.",
          "Executive alignment moments.",
          "Know when to qualify out.",
        ],
        d(
          "Long deals need:",
          [
            "Only relentless discounting",
            "Mutual plans and staged value",
            "Ignoring legal",
            "One email a quarter",
          ],
          1,
          "Process creates progress.",
        ),
      ),
      q(
        "inbound-lead",
        "Case",
        "Hot inbound, cold fit",
        10,
        "Qualification courage.",
        "PLG + sales-assist org.",
        "An inbound lead wants a demo tomorrow but is clearly outside ICP. What do you do?",
        [
          "Qualify against ICP politely.",
          "Redirect to self-serve or partner if fit.",
          "Don’t burn SE time on bad fits.",
          "Capture learning for marketing.",
          "Stay kind — today’s misfit can refer.",
        ],
        d(
          "Outside-ICP inbound should:",
          [
            "Always get a full enterprise demo",
            "Be qualified and redirected appropriately",
            "Be ignored rudely",
            "Be sold anyway for activity metrics",
          ],
          1,
          "Time is inventory.",
        ),
      ),
      q(
        "negotiation",
        "Case",
        "Procurement squeeze",
        15,
        "Commercial negotiation.",
        "Late-stage enterprise.",
        "Procurement asks for a 25% cut and unlimited liability. How do you negotiate?",
        [
          "Separate price from terms.",
          "Trade concessions for term length/commit.",
          "Involve deal desk/legal early.",
          "Protect dangerous terms explicitly.",
          "Have a BATNA.",
        ],
        d(
          "Smart negotiation:",
          [
            "Accept all terms to close",
            "Trade value and protect risky clauses",
            "Avoid Legal",
            "Argue only on ego",
          ],
          1,
          "Bad terms are expensive revenue.",
        ),
      ),
      q(
        "why-ae",
        "Closing",
        "Why sell this",
        8,
        "Motivation close.",
        "Hiring manager final.",
        "Why this product and sales motion?",
        [
          "Customer problem you believe in.",
          "Motion fit (enterprise vs transactional).",
          "How you ramp in 90 days.",
          "Ask about ramp expectations and support.",
          "Avoid “I’m competitive” as the only answer.",
        ],
        d(
          "Strong AE closes show:",
          [
            "Only commission hunger",
            "Problem belief + motion fit + ramp plan",
            "No curiosity about the product",
            "Guaranteed quota bravado",
          ],
          1,
          "Belief + plan beats swagger.",
        ),
      ),
    ],
  },
  {
    slug: "devops-sre",
    role: "DevOps / SRE",
    setting: "Platform team at a scale-up",
    blurb: "Reliability, incidents, IaC, and toil reduction.",
    scenarios: [
      q(
        "slo-design",
        "Technical",
        "Define SLOs for checkout",
        18,
        "Reliability objectives that matter.",
        "SRE interview for a payments-adjacent service.",
        "How would you set SLOs for checkout availability and latency?",
        [
          "User journey first, not CPU graphs.",
          "SLI that matches experience.",
          "Targets from history + business risk.",
          "Error budgets and consequences.",
          "Alert on symptoms, not every cause.",
        ],
        d(
          "Good SLOs start from:",
          [
            "Random 99.999% everywhere",
            "User journeys and business risk",
            "Only disk space",
            "Ignoring error budgets",
          ],
          1,
          "Users define reliability.",
        ),
      ),
      q(
        "incident-command",
        "Behavioral",
        "You are incident commander",
        15,
        "IC skills under stress.",
        "On-call heavy SRE role.",
        "You’re IC for a regional outage. How do you run the first 30 minutes?",
        [
          "Declare severity and roles.",
          "Stabilize; parallelize investigation.",
          "Comms cadence to stakeholders.",
          "Avoid fix-flailing without hypotheses.",
          "Hand off cleanly if needed.",
        ],
        d(
          "IC priority one:",
          [
            "Writing a perfect RCA first",
            "Clear roles, stabilize, communicate",
            "Debating tooling brands",
            "Muting the status channel",
          ],
          1,
          "Command brings order to chaos.",
        ),
      ),
      q(
        "toil",
        "Case",
        "Kill recurring toil",
        12,
        "Automation judgment.",
        "Platform SRE screen.",
        "On-call spends hours weekly restarting a flaky job. How do you reduce toil?",
        [
          "Measure frequency and cost.",
          "Fix root cause vs bandage scripts.",
          "Automate if still needed.",
          "Add coverage tests/alerts.",
          "Track toil budget with the team.",
        ],
        d(
          "Best long-term move:",
          [
            "Only document the restart steps forever",
            "Remove root cause; automate what’s left",
            "Hire more humans to restart",
            "Disable monitoring",
          ],
          1,
          "Toil is a bug in the system of work.",
        ),
      ),
      q(
        "iac-review",
        "Technical",
        "Risky Terraform change",
        15,
        "Safe infrastructure change.",
        "DevOps interview with IaC focus.",
        "A PR destroys and recreates a production database resource. How do you review?",
        [
          "Plan output carefully.",
          "Stateful resources need migration plans.",
          "Require backups and rollback.",
          "Staging proof when possible.",
          "Block reckless applies.",
        ],
        d(
          "On stateful destroy/recreate:",
          [
            "Approve quickly to move fast",
            "Demand migration, backup, and rollback plan",
            "Apply from a laptop with no review",
            "Ignore plan output",
          ],
          1,
          "Data loss isn’t a flex.",
        ),
      ),
      q(
        "cost-spike",
        "Case",
        "Cloud bill doubled",
        15,
        "Cost as a reliability concern.",
        "FinOps-aware platform team.",
        "AWS bill doubled WoW. How do you investigate?",
        [
          "Break down by service/account/tag.",
          "Correlate with deploys and traffic.",
          "Look for runaway jobs, logs, data transfer.",
          "Short-term containment + durable fix.",
          "Add budgets/alerts after.",
        ],
        d(
          "First investigation step:",
          [
            "Delete the production account",
            "Attribute spend by service and change correlation",
            "Ignore it as “scale”",
            "Only email Finance",
          ],
          1,
          "Attribution before action.",
        ),
      ),
      q(
        "security-patch",
        "Behavioral",
        "Critical CVE on Friday",
        12,
        "Risk-based patching.",
        "SRE shared with security.",
        "A critical CVE hits your base image Friday 4pm. What’s your process?",
        [
          "Assess exposure and exploitability.",
          "Patch priority systems first.",
          "Communicate freeze/risk to partners.",
          "Don’t skip change control blindly — adapt it.",
          "Verify and document.",
        ],
        d(
          "Friday CVE response should:",
          [
            "Wait until Monday always",
            "Assess exposure and patch by risk",
            "Shut down the company Slack",
            "Ignore if it’s after hours",
          ],
          1,
          "Risk-based urgency.",
        ),
      ),
      q(
        "ci-failing",
        "Technical",
        "Flaky CI blocking releases",
        12,
        "Pipeline reliability.",
        "DevOps supporting many app teams.",
        "CI flakes block 20% of merges. Approach?",
        [
          "Quantify flake rate by test.",
          "Quarantine with visibility — don’t hide forever.",
          "Fix top offenders with owners.",
          "Improve determinism (time, network, order).",
          "Track pipeline SLO.",
        ],
        d(
          "Flaky tests should be:",
          [
            "Ignored silently",
            "Measured, quarantined transparently, then fixed",
            "Deleted without discussion",
            "Rerun 50 times as the only strategy",
          ],
          1,
          "Visibility prevents rot.",
        ),
      ),
      q(
        "oncall-burnout",
        "Behavioral",
        "Unsustainable pages",
        12,
        "Human reliability.",
        "SRE culture interview.",
        "Pages wake the team three times a night. What do you change?",
        [
          "Alert quality: symptom-based, actionable.",
          "Fix noisy causes.",
          "Load-balance rotations; follow-the-sun if needed.",
          "Error budget policy for feature freezes.",
          "Measure MTTR and page load.",
        ],
        d(
          "Burnout from pages is fixed by:",
          [
            "Telling people to be tougher",
            "Better alerts, fewer causes, fairer rotation",
            "Removing all monitoring",
            "Only hiring more martyrs",
          ],
          1,
          "Sustainable on-call is a design problem.",
        ),
      ),
      q(
        "migration",
        "Case",
        "Kubernetes migration",
        20,
        "Migration risk management.",
        "Platform modernization interview.",
        "Leadership wants all services on Kubernetes in a quarter. How do you plan?",
        [
          "Goals and non-goals.",
          "Strangler pattern; don’t big-bang.",
          "Platform paved roads first.",
          "Success metrics and rollback.",
          "Training and support model for app teams.",
        ],
        d(
          "Safer migrations use:",
          [
            "A single weekend cutover for everything",
            "Incremental moves with paved roads and rollback",
            "No metrics",
            "Forbidding rollbacks",
          ],
          1,
          "Incrementalism saves companies.",
        ),
      ),
      q(
        "why-sre",
        "Closing",
        "Why this platform team",
        8,
        "Motivation close.",
        "Hiring manager final.",
        "Why SRE/DevOps here, and what reliability win do you want in 90 days?",
        [
          "Their scale/reliability challenge.",
          "A concrete toil or SLO win.",
          "How you partner with product eng.",
          "Ask about on-call expectations.",
          "Avoid “I like servers” only.",
        ],
        d(
          "Strong closes name:",
          [
            "Only tool logos",
            "A reliability problem and a 90-day win",
            "No on-call questions",
            "Guaranteed zero incidents forever",
          ],
          1,
          "Outcomes over tooling religion.",
        ),
      ),
    ],
  },
  {
    slug: "people-ops",
    role: "People Operations",
    setting: "High-growth startup HR/People",
    blurb: "Hiring systems, employee relations, and org design judgment.",
    scenarios: [
      q(
        "hiring-process",
        "Case",
        "Fix a broken interview loop",
        18,
        "Structured hiring.",
        "People ops / recruiting ops interview.",
        "Engineering hires take 90 days and candidates drop after onsite. How do you improve?",
        [
          "Map the funnel with data.",
          "Scorecards and trained interviewers.",
          "Candidate experience: speed and clarity.",
          "Remove redundant rounds.",
          "Partner with hiring managers on SLAs.",
        ],
        d(
          "Slow loops usually need:",
          [
            "More surprise interview rounds",
            "Funnel data, structure, and faster decisions",
            "Ghosting candidates",
            "Only raising comp blindly",
          ],
          1,
          "Process + speed + structure.",
        ),
      ),
      q(
        "performance-issue",
        "Behavioral",
        "Manager avoids feedback",
        15,
        "Coach managers through conflict.",
        "HRBP-style interview.",
        "A manager wants to exit someone they never coached. How do you handle it?",
        [
          "Review documentation and prior feedback.",
          "Coach for a fair performance plan if appropriate.",
          "Protect legal/process fairness.",
          "Don’t rubber-stamp surprise exits.",
          "Support dignity either path.",
        ],
        d(
          "People ops should:",
          [
            "Approve any exit instantly",
            "Ensure fairness, coaching, and clear process",
            "Ignore legal risk",
            "Discuss the case in public Slack",
          ],
          1,
          "Fairness protects people and the company.",
        ),
      ),
      q(
        "comp-band",
        "Case",
        "Offer above band",
        12,
        "Equity and exceptions.",
        "Comp-adjacent people role.",
        "A hiring manager wants an offer 20% above band for a “unicorn.” Approach?",
        [
          "Market data and internal equity.",
          "Exception criteria and approval path.",
          "Alternatives: level, scope, sign-on.",
          "Document the exception.",
          "Watch compression with peers.",
        ],
        d(
          "Above-band offers need:",
          [
            "A handshake in the hallway only",
            "Data, equity check, and documented exception",
            "Secret side deals",
            "Ignoring peer compression",
          ],
          1,
          "Exceptions without process become culture debt.",
        ),
      ),
      q(
        "reorg-comms",
        "Case",
        "Announce a reorg",
        15,
        "Change communication.",
        "People partner to leadership.",
        "Leadership is reorganizing two teams. How do you plan communications?",
        [
          "Who needs to know what, when.",
          "Manager talking points first.",
          "Employee FAQ and channels for questions.",
          "Avoid rumors by timing carefully.",
          "Follow-up pulse after change.",
        ],
        d(
          "Reorg comms fail when:",
          [
            "Managers are briefed first",
            "Employees hear via rumor before leaders speak",
            "There’s an FAQ",
            "There’s a follow-up pulse",
          ],
          1,
          "Vacuum fills with fear.",
        ),
      ),
      q(
        "dei-hiring",
        "Case",
        "Improve hiring diversity",
        15,
        "Inclusive hiring systems.",
        "People team with DEI goals.",
        "How would you improve diversity in our engineering hiring without tokenism?",
        [
          "Widen top-of-funnel sources.",
          "Structured interviews reduce bias.",
          "Train panels; diverse panels where possible.",
          "Measure pass-through rates.",
          "Focus on systems, not quotas theater.",
        ],
        d(
          "Sustainable DEI hiring emphasizes:",
          [
            "Lowering the bar secretly",
            "Sourcing + structured evaluation + measurement",
            "Only PR statements",
            "Ignoring candidate experience",
          ],
          1,
          "Systems change outcomes.",
        ),
      ),
      q(
        "policy-gray",
        "Behavioral",
        "Remote work gray area",
        12,
        "Policy judgment.",
        "People ops in a hybrid company.",
        "An employee asks to work abroad for 3 months; policy is unclear. What do you do?",
        [
          "Check legal/tax/security implications.",
          "Don’t invent policy solo — align stakeholders.",
          "Decide with consistent criteria.",
          "Document for the next request.",
          "Communicate kindly either way.",
        ],
        d(
          "Gray policy requests need:",
          [
            "A random yes to be nice",
            "Risk review and consistent documented criteria",
            "Public shaming",
            "Ignoring tax/security",
          ],
          1,
          "Consistency is fairness.",
        ),
      ),
      q(
        "onboarding",
        "Case",
        "Fix first-week onboarding",
        12,
        "Employee experience design.",
        "People ops owning onboarding.",
        "New hires say week one is chaotic. How would you redesign it?",
        [
          "Define day-1 outcomes.",
          "Access, buddy, manager 1:1, role clarity.",
          "Reduce tool overload.",
          "Feedback loop at day 7/30.",
          "Shared ownership with IT/hiring managers.",
        ],
        d(
          "Great onboarding prioritizes:",
          [
            "30 password resets and no human contact",
            "Access, belonging, and role clarity early",
            "Only swag",
            "A 200-page PDF",
          ],
          1,
          "Clarity + connection.",
        ),
      ),
      q(
        "conflict-mediation",
        "Behavioral",
        "Teammate conflict",
        15,
        "Mediation basics.",
        "HRBP interview.",
        "Two senior ICs refuse to collaborate. How do you intervene?",
        [
          "Hear each side separately first.",
          "Focus on behavior and impact.",
          "Facilitate a structured conversation.",
          "Engage their manager on accountability.",
          "Know when formal processes apply.",
        ],
        d(
          "Mediation should focus on:",
          [
            "Personality labels",
            "Behaviors, impact, and agreements",
            "Forced friendship",
            "Ignoring managers",
          ],
          1,
          "Behavior is coachable; drama isn’t the goal.",
        ),
      ),
      q(
        "headcount",
        "Case",
        "Headcount planning",
        15,
        "Workforce planning judgment.",
        "People ops with finance partnership.",
        "Every team asks for more headcount. How do you prioritize?",
        [
          "Company goals and constraints.",
          "ROI / bottleneck evidence.",
          "Alternatives: contractors, scope cuts, tooling.",
          "Phased hiring plan.",
          "Transparent criteria to leaders.",
        ],
        d(
          "Headcount prioritization needs:",
          [
            "Equal yes to everyone",
            "Goal alignment and bottleneck evidence",
            "Only whoever yells loudest",
            "No finance input",
          ],
          1,
          "Constraints force strategy.",
        ),
      ),
      q(
        "why-people",
        "Closing",
        "Why people ops here",
        8,
        "Motivation close.",
        "Hiring manager final.",
        "Why People Ops at this stage of company?",
        [
          "Stage-specific people problems.",
          "Systems you want to build.",
          "How you partner with leaders.",
          "Ask how success is measured.",
          "Avoid “I just love people” only.",
        ],
        d(
          "Strong closes cite:",
          [
            "Only soft clichés",
            "Stage problems + systems you’ll build",
            "No partnership mindset",
            "Gossip interest",
          ],
          1,
          "People ops is systems work.",
        ),
      ),
    ],
  },
  {
    slug: "operations",
    role: "Operations Manager",
    setting: "Marketplace / logistics-heavy business",
    blurb: "Process design, vendor management, and operational firefighting.",
    scenarios: [
      q(
        "process-break",
        "Case",
        "Fulfillment error spike",
        18,
        "Root cause in operations.",
        "Ops manager interview at a marketplace.",
        "Wrong-item rate jumped 2x this week. How do you respond?",
        [
          "Quantify impact and segments.",
          "Map the process; find change points.",
          "Contain: checks, pauses, comms.",
          "Fix root cause with owners.",
          "Add a leading indicator metric.",
        ],
        d(
          "First ops response:",
          [
            "Blame a single warehouse worker publicly",
            "Measure, contain, then root-cause",
            "Ignore until month end",
            "Only send apology coupons forever",
          ],
          1,
          "Containment + cause.",
        ),
      ),
      q(
        "vendor-sla",
        "Case",
        "Vendor missing SLA",
        15,
        "Vendor management.",
        "Ops owning 3PL relationships.",
        "Your 3PL missed SLA three weeks running. What’s your playbook?",
        [
          "Facts and contract remedies.",
          "Joint ops review with data.",
          "Short-term mitigations (buffer, alternate).",
          "Escalation path and exit criteria.",
          "Protect customer experience meanwhile.",
        ],
        d(
          "Vendor misses need:",
          [
            "Hope alone",
            "Data, remedies, mitigation, and exit criteria",
            "Immediate lawsuit tweets",
            "Hiding issues from leadership",
          ],
          1,
          "Manage vendors like systems.",
        ),
      ),
      q(
        "capacity-plan",
        "Case",
        "Holiday surge",
        15,
        "Capacity planning.",
        "Seasonal volume business.",
        "Volume will 3x in six weeks. How do you prepare?",
        [
          "Forecast by node/channel.",
          "Labor, inventory, systems constraints.",
          "Risk scenarios low/base/high.",
          "Early hiring/training and vendor surge.",
          "War-room metrics for peak weeks.",
        ],
        d(
          "Surge prep prioritizes:",
          [
            "Waiting to see what happens",
            "Forecast-driven capacity and risk scenarios",
            "Only discounting prices",
            "Cutting QA to go faster",
          ],
          1,
          "Plan beats panic.",
        ),
      ),
      q(
        "cross-team",
        "Behavioral",
        "Product ships without ops input",
        12,
        "Influence without authority.",
        "Ops partner to product.",
        "Product launches a feature that breaks warehouse workflows. What do you do afterward — and next time?",
        [
          "Stabilize customer impact now.",
          "Blameless review of the miss.",
          "Create a launch checklist with ops gates.",
          "Embed ops in planning earlier.",
          "Measure launch readiness.",
        ],
        d(
          "After a broken launch, durable fix is:",
          [
            "Yelling once in Slack",
            "Process gates and earlier embedding",
            "Blocking all product work forever",
            "Ignoring it",
          ],
          1,
          "Turn pain into process.",
        ),
      ),
      q(
        "kpi-choice",
        "Case",
        "Pick ops KPIs",
        12,
        "Metric design for ops.",
        "Ops leader screen.",
        "Which 5 KPIs would you put on a weekly ops review and why?",
        [
          "Customer outcome metrics (OTIF, quality).",
          "Cost/efficiency.",
          "Leading indicators (backlog, aging).",
          "People metrics (safety, overtime).",
          "Avoid vanity activity counts.",
        ],
        d(
          "Ops KPI sets should include:",
          [
            "Only emails sent",
            "Outcomes, cost, leading indicators, people/safety",
            "Forty equally weighted charts",
            "No customer metrics",
          ],
          1,
          "Balance outcomes and leading signals.",
        ),
      ),
      q(
        "automation",
        "Case",
        "Automate a manual check",
        12,
        "Automation ROI.",
        "Ops excellence interview.",
        "Analysts manually check 500 orders/day for fraud flags. Automate?",
        [
          "Error rates and cost of manual work.",
          "False positive/negative risk.",
          "Human-in-the-loop design.",
          "Rollout with shadow mode.",
          "Monitor after launch.",
        ],
        d(
          "Automation decisions need:",
          [
            "Automating everything immediately",
            "Risk, ROI, and staged rollout",
            "No monitoring",
            "Removing all humans forever on day one",
          ],
          1,
          "Shadow mode saves you.",
        ),
      ),
      q(
        "crisis-weather",
        "Behavioral",
        "Regional disruption",
        15,
        "Crisis operations.",
        "Marketplace with physical logistics.",
        "A storm shuts a key hub. How do you run the day?",
        [
          "Customer messaging and ETAs.",
          "Reroute volume; protect perishable/critical.",
          "Stand up a cross-functional bridge.",
          "Document decisions for claims later.",
          "After-action for network resilience.",
        ],
        d(
          "Disruption days prioritize:",
          [
            "Silence to avoid panic",
            "Customer truth, reroutes, and a command bridge",
            "Only internal blame",
            "Normal KPIs with no adjustment",
          ],
          1,
          "Truth + triage.",
        ),
      ),
      q(
        "cost-out",
        "Case",
        "Cut ops cost 10%",
        15,
        "Cost without wrecking service.",
        "Ops + finance partnership interview.",
        "You must reduce ops cost 10% without tanking NPS. Approach?",
        [
          "Cost stack analysis.",
          "Cut waste before cutting service.",
          "Model service impact of each lever.",
          "Pilot changes.",
          "Watch leading quality metrics.",
        ],
        d(
          "Cost-outs should:",
          [
            "Slash quality blindly",
            "Target waste with service-impact modeling",
            "Hide NPS drops",
            "Only cut training",
          ],
          1,
          "Service-aware cost discipline.",
        ),
      ),
      q(
        "sop-write",
        "Technical",
        "Write an SOP that sticks",
        10,
        "Process documentation that people use.",
        "Ops manager owning SOPs.",
        "How do you create an SOP teams will actually follow?",
        [
          "Co-write with the people doing the work.",
          "Short, visual, versioned.",
          "Train and certify.",
          "Audit adherence kindly.",
          "Update when reality changes.",
        ],
        d(
          "SOPs fail when they:",
          [
            "Are co-created and trained",
            "Are unread novels written in isolation",
            "Have owners",
            "Get updated",
          ],
          1,
          "Adoption is the metric.",
        ),
      ),
      q(
        "why-ops",
        "Closing",
        "Why operations here",
        8,
        "Motivation close.",
        "Hiring manager final.",
        "Why ops at this company, and what would you stabilize first?",
        [
          "Operational bottleneck you noticed.",
          "How you balance service and cost.",
          "30/60/90 listening + quick win.",
          "Ask how ops success is measured.",
          "Avoid “I’m organized” as the whole pitch.",
        ],
        d(
          "Strong ops closes include:",
          [
            "Only that you like spreadsheets",
            "A real bottleneck + grounded ramp plan",
            "No metrics curiosity",
            "Promising zero incidents forever",
          ],
          1,
          "Show you see the system.",
        ),
      ),
    ],
  },
];

export const JOB_TRACKS: JobTrack[] = withExtras([...CORE_JOB_TRACKS, ...BUSINESS_JOB_TRACKS]);

export type InterviewRound = InterviewScenario & {
  trackSlug: string;
  role: string;
  setting: string;
};

export const ROUNDS: InterviewRound[] = JOB_TRACKS.flatMap((track) =>
  track.scenarios.map((s) => ({
    ...s,
    trackSlug: track.slug,
    role: track.role,
    setting: track.setting,
  })),
);

export function getTrack(slug: string): JobTrack | undefined {
  return JOB_TRACKS.find((t) => t.slug === slug);
}

export function getRound(trackSlug: string, scenarioSlug: string): InterviewRound | undefined {
  return ROUNDS.find((r) => r.trackSlug === trackSlug && r.slug === scenarioSlug);
}

export function roundPath(round: InterviewRound): string {
  return `/practice/${round.trackSlug}/${round.slug}`;
}

export const LESSONS = ROUNDS;
export function getLesson(slug: string) {
  return ROUNDS.find((r) => r.slug === slug);
}
